version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    dlm:
      image: adnaneds/deep-oc-dlm
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    dlm-gpu:
      image: adnaneds/deep-oc-dlm:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    dlm-rclone:
      extends:
        service: dlm
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
